Models/ErrorViewModel.cs
namespace ProjetoV.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Pessoa.cs
using Google.Cloud.Firestore;
using System.ComponentModel.DataAnnotations;

namespace ProjetoV.Models
{
    [FirestoreData]
    public class Pessoa
    {
        [Display(Name = "Código Pessoa")]
        public string PessoaId { get; set; } = "";

        [FirestoreProperty]
        public string Nome { get; set; } = "";

        [Display(Name = "CPF")]
        [FirestoreProperty]
        public string Cpf { get; set; } = "";

        [Display(Name = "E-Mail")]
        [FirestoreProperty]
        public string Email { get; set; } = "";

    }
}

Models/Produto.cs
using Google.Cloud.Firestore;
using System.ComponentModel;

namespace ProjetoV.Models
{
    [FirestoreData]
    public class Produto
    {
        [DisplayName("Código do Produto")]
        public string ProdutoId { get; set; }

        [FirestoreProperty]
        public string Nome { get; set; }

        [FirestoreProperty]
        public double Preco { get; set; }

        [FirestoreProperty]
        public int Quantidade { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ProjetoV.Models;

namespace ProjetoV.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/PessoasController.cs
using Google.Cloud.Firestore;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProjetoV.Models;
using Newtonsoft.Json;

namespace ProjetoV.Controllers
{
    public class PessoasController : Controller
    {
        private string diretorio = "C:\\dev\\ProjetoV\\projetov-e92f8-85e16f327b43.json";
        private string projetoId;
        private FirestoreDb _firestoreDb;

        public PessoasController()
        {
            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", diretorio);
            projetoId = "projetov-e92f8";
            _firestoreDb = FirestoreDb.Create(projetoId);
        }

        public async Task<IActionResult> Index()
        {
            Query pessoasQuery = _firestoreDb.Collection("pessoas");
            QuerySnapshot pessoasQuerySnapshot = await pessoasQuery.GetSnapshotAsync();
            List<Pessoa> listaPessoas = new List<Pessoa>();
                
            foreach(DocumentSnapshot documentSnapshot in pessoasQuerySnapshot.Documents)
            {
                if (documentSnapshot.Exists)
                {
                    Dictionary<string, object> pessoa = documentSnapshot.ToDictionary();

                    string json = JsonConvert.SerializeObject(pessoa);
                    Pessoa novaPessoa = JsonConvert.DeserializeObject<Pessoa>(json);
                    novaPessoa.PessoaId = documentSnapshot.Id;

                    listaPessoas.Add(novaPessoa);
                }
            }

            return View(listaPessoas);
        }

        [HttpGet]
        public IActionResult NovaPessoa()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> NovaPessoa(Pessoa pessoa)
        {
            CollectionReference collectionReference = _firestoreDb.Collection("pessoas");
            await collectionReference.AddAsync(pessoa);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> AtualizarPessoa(string pessoaId)
        {
            DocumentReference documentReference = _firestoreDb.Collection("pessoas").Document(pessoaId);
            DocumentSnapshot documentSnapshot = await documentReference.GetSnapshotAsync();

            if (documentSnapshot.Exists)
            {
                Pessoa pessoa = documentSnapshot.ConvertTo<Pessoa>();
                return View(pessoa);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> AtualizarPessoa(Pessoa pessoa)
        {
            DocumentReference documentReferente = _firestoreDb.Collection("pessoas").Document(pessoa.PessoaId);
            await documentReferente.SetAsync(pessoa, SetOptions.Overwrite);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> ExcluirPessoa(string pessoaId)
        {
            DocumentReference documentReference = _firestoreDb.Collection("pessoas").Document(pessoaId);
            await documentReference.DeleteAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/ProdutosController.cs
using Google.Cloud.Firestore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Newtonsoft.Json;
using ProjetoV.Models;

namespace ProjetoV.Controllers 
{
    public class ProdutosController : Controller
    {
        private string diretorio = "C:\\dev\\ProjetoV\\projetov-e92f8-85e16f327b43.json";
        private string projetoId;
        private FirestoreDb _firestoreDb;

        public ProdutosController()
        {
            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", diretorio);
            projetoId = "projetov-e92f8";
            _firestoreDb = FirestoreDb.Create(projetoId);
        }
 
        public async Task<IActionResult> Index()
        {
            Query produtosQuery = _firestoreDb.Collection("produtos");
            QuerySnapshot produtosQuerySnapshot = await produtosQuery.GetSnapshotAsync();
            List<Produto> listaProdutos = new List<Produto>();

            foreach(DocumentSnapshot documentSnapshot in produtosQuerySnapshot.Documents)
            {
                if(documentSnapshot.Exists) 
                {
                    Dictionary<string, object> produto = documentSnapshot.ToDictionary();

                    string json = JsonConvert.SerializeObject(produto);
                    Produto novoProduto = JsonConvert.DeserializeObject<Produto>(json);
                    novoProduto.ProdutoId = documentSnapshot.Id;

                    listaProdutos.Add(novoProduto);
                }
            }
            return View(listaProdutos);
        }

        [HttpGet]
        public IActionResult NovoProduto()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> NovoProduto(Produto produto)
        {
            CollectionReference collectionReference = _firestoreDb.Collection("produtos");
            await collectionReference.AddAsync(produto);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> AtualizarProduto(string produtoId)
        {
            DocumentReference documentReference = _firestoreDb.Collection("produtos").Document(produtoId);
            DocumentSnapshot documentSnapshot = await documentReference.GetSnapshotAsync();

            if (documentSnapshot.Exists)
            {
                Produto produto = documentSnapshot.ConvertTo<Produto>();
                return View(produto);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> AtualizarProduto(Produto produto)
        {
            DocumentReference documentReferente = _firestoreDb.Collection("produtos").Document(produto.ProdutoId);
            await documentReferente.SetAsync(produto, SetOptions.Overwrite);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> ExcluirProduto(string produtoId)
        {
            DocumentReference documentReference = _firestoreDb.Collection("produtos").Document(produtoId);
            await documentReference.DeleteAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Projeto Interdisciplinar V</h1>
    <h3>Sistema de controle de estoque</h3>    
    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoas" asp-action="Index">
                                <button class="botao-pessoas">Cadastro de Pessoas</button>                                
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">
                                <button class="botao-produtos">Cadastros de Produtos</button>
                            </a>
                        </li>
                    </ul>
                </div>
    
</div>


<style>
    .botao-pessoas{
        background-color: #4CAF50;
        border: none;
        color: white;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 4px;
        transition-duration: 0.4s;
    }

    .botao-produtos
    {
        background-color: #f16156;
        border: none;
        color: white;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 4px;
        transition-duration: 0.3s;
    }

        .botao-pessoas:hover {
        background-color: #357e38;
        }

        .botao-produtos:hover {
        background-color: #cb4d44;            
        }
</style>

Views/Pessoas/AtualizarPessoa.cshtml
@model ProjetoV.Models.Pessoa

@{
    ViewData["Title"] = "AtualizarPessoa";
}

<h1>AtualizarPessoa</h1>

<h4>Pessoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AtualizarPessoa">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>            
                <label asp-for="PessoaId" class="control-label"></label>
                <input asp-for="PessoaId" hidden />                           
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cpf" class="control-label"></label>
                <input asp-for="Cpf" class="form-control" />
                <span asp-validation-for="Cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Pessoas/Index.cshtml
@model IEnumerable<ProjetoV.Models.Pessoa>

@{
    ViewData["Title"] = "Pessoas";
}

<h1>Pessoas</h1>

<p>
    <a asp-action="NovaPessoa">
        <button class="botao-criar" type="submit">Cadastrar Pessoa</button>
    </a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PessoaId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PessoaId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cpf)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    <div class="td-botoes">
                    <a asp-action="AtualizarPessoa" asp-route-pessoaId="@item.PessoaId">
                        <button class="botao-editar" type="submit">Atualizar</button>
                    </a>

                    <form asp-action="ExcluirPessoa" asp-route-pessoaId="@item.PessoaId">
                        <button type="submit" class="botao-excluir">Excluir</button>
                    </form>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>


@* --- Estilo dos botões --- *@
<style>
    .botao-editar, .botao-excluir, .botao-criar {
        background-color: #4CAF50;
        border: none;
        color: white;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 4px;
        transition-duration: 0.3s;
    }

        .botao-criar:hover {
            background-color: #2fa597;
        }

        .botao-editar:hover {
            background-color: #3e8e41;
        }

        .botao-excluir:hover {
            background-color: #f44336;
        }
</style>

Views/Pessoas/NovaPessoa.cshtml
@model ProjetoV.Models.Pessoa

@{
    ViewData["Title"] = "Nova Pessoa";
}

<h1>Nova Pessoa</h1>

<h4>Pessoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="NovaPessoa">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cpf" class="control-label">CPF</label>
                <input asp-for="Cpf" class="form-control" />
                <span asp-validation-for="Cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">E-Mail</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">
        <button>Voltar</button>
    </a>
</div>

Views/Produtos/AtualizarProduto.cshtml
@model ProjetoV.Models.Produto

@{
    ViewData["Title"] = "AtualizarProduto";
}

<h1>AtualizarProduto</h1>

<h4>Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AtualizarProduto">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <label asp-for="ProdutoId" class="control-label"></label>
            <input asp-for="ProdutoId" hidden />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantidade" class="control-label"></label>
                <input asp-for="Quantidade" class="form-control" />
                <span asp-validation-for="Quantidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Produtos/Index.cshtml
@model IEnumerable<ProjetoV.Models.Produto>

@{
    ViewData["Title"] = "Produtos";
}

<h1>Produtos</h1>

<p>
    <a asp-action="NovoProduto">
        <button class="botao-criar" type="submit">Cadastrar Produto</button>
    </a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProdutoId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantidade)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProdutoId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Preco)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantidade)
                </td>
                <td>
                    <div class="td-botoes">
                        <a asp-action="AtualizarProduto" asp-route-produtoId="@item.ProdutoId">
                            <button class="botao-editar" type="submit">Atualizar</button>
                        </a>

                        <form asp-action="ExcluirProduto" asp-route-produtoId="@item.ProdutoId">
                            <button type="submit" class="botao-excluir">Excluir</button>
                        </form>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
@* --- Estilo dos botões --- *@
<style>
    .botao-editar, .botao-excluir, .botao-criar {
        background-color: #4CAF50;
        border: none;
        color: white;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 4px;
        transition-duration: 0.3s;
    }

        .botao-criar:hover {
            background-color: #2fa597;
        }

        .botao-editar:hover {
            background-color: #3e8e41;
        }

        .botao-excluir:hover {
            background-color: #f44336;
        }
</style>

Views/Produtos/NovoProduto.cshtml
@model ProjetoV.Models.Produto

@{
    ViewData["Title"] = "Novo Produto";
}

<h1>Novo Produto</h1>

<h4>Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="NovoProduto">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantidade" class="control-label"></label>
                <input asp-for="Quantidade" class="form-control" />
                <span asp-validation-for="Quantidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto V</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoV.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjetoV</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoas" asp-action="Index">Pessoas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProjetoV - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>